variable "ami_id" {}
variable "instance_type" {}
variable "public_subnet_id" {}
variable "private_subnet_id" {}
variable "bastion_sg_id" {}
variable "private_sg_id" {}
variable "instance_profile_name" {}
variable "public_instance_name" {}
variable "private_instance_name" {}
